# Generated by Django 2.1.5 on 2019-01-27 07:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Greens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='菜名', max_length=20, verbose_name='菜名')),
                ('brief', models.CharField(default='', help_text='简短介绍', max_length=200, verbose_name='简短介绍')),
                ('tips', models.CharField(default='', help_text='小贴士', max_length=200, verbose_name='小贴士')),
                ('views', models.IntegerField(default=0, help_text='浏览量', max_length=10, verbose_name='浏览量')),
                ('collect', models.IntegerField(default=0, help_text='收藏量', max_length=10, verbose_name='收藏量')),
                ('makes', models.CharField(default='', help_text='步骤', max_length=1000, verbose_name='步骤')),
                ('burden', models.CharField(default='', help_text='用料', max_length=1000, verbose_name='用料')),
            ],
            options={
                'verbose_name': '菜',
                'verbose_name_plural': '菜',
            },
        ),
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='类别名', max_length=30, verbose_name='类别名')),
                ('brief', models.CharField(default='', help_text='简短介绍', max_length=200, verbose_name='简短介绍')),
                ('category_level', models.IntegerField(choices=[(1, '一级类目'), (2, '二级类目'), (3, '三级类目')], help_text='类目级别', verbose_name='类目级别')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('parent_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_cat', to='app.MenuCategory', verbose_name='父类别')),
            ],
            options={
                'verbose_name': '菜单类别',
                'verbose_name_plural': '菜单类别',
            },
        ),
        migrations.AddField(
            model_name='greens',
            name='category',
            field=models.ManyToManyField(to='app.MenuCategory'),
        ),
    ]
