# Generated by Django 2.1.5 on 2019-01-31 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190127_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='menucategory',
            name='category_way',
            field=models.IntegerField(choices=[(1, '分类'), (2, '食材')], default=3, help_text='分类方式', verbose_name='分类方式'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='greens',
            name='category',
            field=models.ManyToManyField(help_text='类别', to='app.MenuCategory', verbose_name='类别'),
        ),
        migrations.AlterField(
            model_name='greens',
            name='collect',
            field=models.IntegerField(default=0, help_text='收藏量', verbose_name='收藏量'),
        ),
        migrations.AlterField(
            model_name='greens',
            name='views',
            field=models.IntegerField(default=0, help_text='浏览量', verbose_name='浏览量'),
        ),
    ]
