# Generated by Django 2.1.5 on 2019-02-01 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190131_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(default='', help_text='图片地址', max_length=200, verbose_name='图片地址')),
                ('index', models.IntegerField(default=0, verbose_name='轮播顺序')),
                ('category', models.ForeignKey(help_text='类别', on_delete=django.db.models.deletion.CASCADE, to='app.MenuCategory', verbose_name='类别')),
            ],
            options={
                'verbose_name': '轮播类',
                'verbose_name_plural': '轮播类',
            },
        ),
    ]
