# Generated by Django 2.1.5 on 2019-02-02 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='greens',
            name='img',
            field=models.CharField(blank=True, default='', help_text='封面图', max_length=200, null=True, verbose_name='封面图'),
        ),
    ]
