# Generated by Django 2.1.5 on 2019-02-25 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20190202_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='menucategory',
            name='islast_level',
            field=models.BooleanField(default=False, help_text='是否是最后级别', verbose_name='是否是最后级别'),
        ),
    ]
