# Generated by Django 2.1.5 on 2019-02-25 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20190225_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menucategory',
            name='islast_level',
            field=models.BooleanField(default=False, help_text='是否是最后级别', verbose_name='是否是最后级别'),
        ),
    ]
